name: Github Actions Push

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  init:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v3
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: yarn install
      - name: Start local Redis
        run: |
          docker run -d -p 6379:6379 --name redis redis:alpine
      - name: linter check
        run: yarn lint
      - name: typecheck
        run: yarn typecheck
      - name: runnig unit tests
        run: yarn test
      - name: runnig e2e tests
        run: yarn test:e2e
      - name: build project
        run: yarn build
      - name: Stop Redis
        run: |
          docker stop redis
          docker rm redis
